# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ItemMapCropper
                                 A QGIS plugin
 This plugin crops (resizes) the map item on a layout to precisely fit a map layer.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-21
        copyright            : (C) 2021 by P. van de Geer
        email                : pvandegeer@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ItemMapCropper class from file ItemMapCropper.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .itemmap_cropper import ItemMapCropper
    return ItemMapCropper(iface)
